### ISSUE TITLE
single apostrophe (') incorrectly parsed as option link

### ISSUE THREAD

**Issue by justinmk** [vigoux/tree-sitter-vimdoc#8] opened 2022-08-29 14:53 UTC
Sample text (from api.txt):

```
Example:

Let's set an extmark at the first row (row=0) and third column (column=2).
|api-indexing| Passing id=0 creates a new mark and returns the id: >

      01 2345678
    0 ex|ample..
<        ^ extmark position
>
    let g:mark_ns = nvim_create_namespace('myplugin')
    let g:mark_id = nvim_buf_set_extmark(0, g:mark_ns, 0, 2, {})
<
We can get the mark by its id: >
```

The `'` char in `Let's` confuses the parser, and lots of errors follow.

**Comment by vigoux** [comment] 2022-08-29 20:23
Kind of expected, I'll see what I can do!

**Comment by vigoux** [comment] 2022-08-31 06:55
Could you confirm the issue is fixed on your end too ?

**Closed** 2022-08-31 06:54 UTC

**Comment by justinmk** [comment] 2022-09-02 04:06
Nice! I checked all single-quote cases in api.txt and couldn't find any issues. Thanks @vigoux !

<img width="777" alt="image" src="https://user-images.githubusercontent.com/1359421/188056772-f6e87515-6f5c-4b1f-bbfa-a6ec2edb0a27.png">
